# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0adcec92292b6390cab3d572211b64a38e1514294080bc8a53ce3c4d07989f7cdc62a7d829b656d9bbba338ec56a9a8ef530d56f0a1b5c36e01a3f309722a46a

test:
  secret_key_base: 3d664f18d2e34ffe882a5773eb6d4091f6dec1a027aa5f1cc10636a17a47f1392818b87fde4d391d8dfd5a27d4ab5664c7515f7c15c875e0592e31dd8199fa79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
